<%@ page session="true"  import="java.sql.*,java.util.*,java.text.*,java.util.Date,java.text.SimpleDateFormat,pkgPmegpNew.DBCon" %>

<html>

<head>
<link rel="stylesheet" href="css/pmegpdashboard3.css">
   
</head>
<body>

<DIV class="w3-container">
	<DIV id="id01" class="w3-modal">
    <DIV class="w3-modal-content">
      <DIV class="w3-container">
        <SPAN onClick="document.getElementById('id01').style.display='none'" class="w3-button w3-display-topright">&times;</SPAN>
      <BR><BR>
	    <IMG src="02.gif" width="100%" height="132">
		<BR><BR>

		<TABLE width="571" border="1" id="customers" align="center">
  <TR>
    <TD width="234"><SPAN class="style1"><STRONG>Website Address </STRONG></SPAN></TD>
    <TD width="321"><SPAN class="style1"><STRONG><A href="https://www.udyami.org.in" target="_blank">https://www.udyami.org.in</A></STRONG></SPAN></TD>
    </TR>
  <TR>
    <TD><SPAN class="style1"><STRONG>Contact no for online EDP </STRONG></SPAN></TD>
    <TD><SPAN class="style1"><STRONG>07526000333/07526000555</STRONG></SPAN></TD>
    </TR>
  <TR>
    <TD><SPAN class="style1"><STRONG>Email</STRONG></SPAN></TD>
    <TD><SPAN class="style1"><STRONG>helpdesk@udyami.org.in</STRONG></SPAN></TD>
    </TR>
</TABLE>
 <BR>
  <P align="center"><span class="box1"><STRONG><A href="../pmegphome/EDP_CIRCULAR_15.11.2019.pdf" style="color:#FFFFFF " class="myButton3" target="_blank">DOWNLOAD ONLINE EDP TRAINING CIRCULAR</A></span></P>
	  <BR>
	 <P align="center"><A href="https://www.udyami.org.in" style="color:#FFFFFF " class="box1" target="_blank">CLICK HERE FOR ONLINE EDP TRAINING </A></P>
	  <BR>
		<P align="center">
		  <input name="button" type="button" class="box1" onClick="showHideDiv('divMsg')" value="SHOW FAQ ON PMEGP ONLINE EDP TRAINING"/>
		</P>
		<BR>
		
		<DIV id="divMsg" style="display:none" >
         <TABLE id="customers">
			<TR>
			  <TH width="45"><DIV align="center">Sr. No. </DIV></TH>
			  <TH width="483"><DIV align="center">Question</DIV></TH>
			  <TH width="802"><DIV align="center">Answer</DIV></TH>
		    </TR>
			<TR>
			  <TD>1</TD>
			  <TD>What  is online EDP portal address?</TD>
			  <TD>PMEGP  online EDP portal address is <A href="http://www.udyami.org.in">www.udyami.org.in</A></TD>
		    </TR>
			<TR>
			  <TD>2</TD>
			  <TD>How  can I download Online EDP Mobile App?</TD>
			  <TD><P>You can download by searching "Udyomi" in Mobile PlayStore App and install accordingly.</P></TD>
		    </TR>
			<TR>
			  <TD>3</TD>
			  <TD>Who are eligible for Online EDP Training? </TD>
			  <TD><P>Applicants  whose PMEGP loan has been sanctioned and not completed online EDP training form  any institute.</P></TD>
		    </TR>
			<TR>
			  <TD>4</TD>
			  <TD>What is the EDP Online Training Fees? </TD>
			  <TD>It is  free of cost for PMEGP beneficiary whose application has been sanctioned by  bank and not taken any training from RSETI/RUDSETI and other eligible institute  as per guidelines.</TD>
		    </TR>
			<TR>
			  <TD>5</TD>
			  <TD>What is the duration of the Training?</TD>
			  <TD><P>15  days is the duration of the Training Modules.</P></TD>
		    </TR>
			<TR>
			  <TD>6</TD>
			  <TD>How to register Online EDP Training?</TD>
			  <TD>By using  registered mobile number in PMEGP E-Portal you can register for Online EDP  training.</TD>
		    </TR>
			<TR>
			  <TD>7</TD>
			  <TD>How to get EDP Certificate?</TD>
			  <TD><P>A  certificate and letter of appreciation will be generated by the portal on  completion of training.</P></TD>
		    </TR>
			<TR>
			  <TD>8</TD>
			  <TD>What is the Online EDP Training helpdesk Contact Details?</TD>
			  <TD><P>Contact  Numbers is 07526000333/ 07526000555</P>
			    <P>E-mail id: <A href="mailto:helpdesk@udyami.org.in">helpdesk@udyami.org.in</A> </P></TD>
		    </TR>
			<TR>
			  <TD>9</TD>
			  <TD>What is additional benefit of the EDP online Portal?</TD><TD>Beside  Online EDP training beneficiary can download projects reports, Industrial  Documentaries, Expert Episodes, Guidance for Statutory Registration and various  Government grants, Incentives and other related Information for a period of one  year.</TD></TR>
		  </TABLE>
	    </DIV>
		  
		    <P align="center"><A href="EDPFAQ.pdf" style="color:#FFFFFF " class="box1" target="_blank" download>DOWNLOAD FAQ</A></P>
	  <BR>
      </DIV>
    </DIV>
  </DIV>
	
	
	
	
	
	
	</DIV>
	</body>
	<SCRIPT>  
	function showHideDiv(ele) {
				var srcElement = document.getElementById(ele);
				if (srcElement != null) {
					if (srcElement.style.display == "block") {
						srcElement.style.display = 'none';
					}
					else {
						srcElement.style.display = 'block';
					}
					return false;
				}
			}
			
</SCRIPT>   

  
	</HTML>