<%@ page import="java.sql.*"%>
<%@ page import="java.util.*"%>
<%@ page import="java.text.*"%>
<%@ page import="java.util.Date"%>
<%@ page import="java.text.ParseException"%>
<%@ page import="pkgsafal.DBCon"%>

<HTML>

<HEAD>
    <META http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
   


    <SCRIPT src="js/sweetalert.min.js"></SCRIPT>
    <SCRIPT language="javascript" src="js/datetimepicker_css.js"></SCRIPT>

    <TITLE>
        SAFAL
    </TITLE>
    <SCRIPT>
        function submitform() {




            document.form.ins.value = 'I';
            document.form.submit();
        }

    </SCRIPT>
</HEAD>



<BODY onLoad="calculateSum()">



    <%


String CHQ_PRID=request.getParameter("CHQ_PRID")==null?"":(String) request.getParameter("CHQ_PRID");

String PAY_TYPE="";
String PFMS_ADV_NO= ""; 
String PAY_ORD_DT= "";
String PAYEE_NM = "";
String BUDGET_HEAD="";
String PAYEE_NET_AMT="";
String NET_PAY_MODE="";
String TDS_ON_GST="";
String SBI_TDS="";
String GROSS_AMT="";
String CHQ_PR_DT="";
String CHQ_NO="";
String CHQ_REMARKS="";
String ACT_YN="";
String add_update="I";

DBCon db= new DBCon(); 
db.connect(); 
List values=new ArrayList(); 
List pstm=new ArrayList(); 

if(!CHQ_PRID.equals("")){

StringBuffer poR = new StringBuffer();


poR.append("SELECT CHQ_PRID, "      );
poR.append("PAY_TYPE, ");
poR.append("PFMS_ADV_NO, "      );
poR.append("TO_CHAR(PAY_ORD_DT,'DD-MON-RRRR')AS PAY_ORD_DT , "      );
poR.append("PAYEE_NM, "      );
poR.append("BUDGET_HEAD, "      );
poR.append("PAYEE_NET_AMT, "      );
poR.append("NET_PAY_MODE, "      );
poR.append("TDS_ON_GST, "      );
poR.append("SBI_TDS, ");
poR.append("GROSS_AMT, "      );
poR.append("TO_CHAR(CHQ_PR_DT,'DD-MON-RRRR')AS CHQ_PR_DT , "      );
poR.append("CHQ_NO , "      );
poR.append("CHQ_REMARKS  "      );
poR.append(" FROM ACC_CHQ_PRINT ");
poR.append(" WHERE CHQ_PRID=?  "   );

values.add(CHQ_PRID);
ResultSet rsMain = db.executeSQL(poR.toString(),values);

values.clear();




while (rsMain.next()){

CHQ_PRID=rsMain.getString("CHQ_PRID")==null?"":rsMain.getString("CHQ_PRID");
PAY_TYPE=rsMain.getString("PAY_TYPE")==null?"":rsMain.getString("PAY_TYPE");
PFMS_ADV_NO=rsMain.getString("PFMS_ADV_NO")==null?"":rsMain.getString("PFMS_ADV_NO");
PAY_ORD_DT=rsMain.getString("PAY_ORD_DT")==null?"":rsMain.getString("PAY_ORD_DT");
PAYEE_NM =rsMain.getString("PAYEE_NM")==null?"":rsMain.getString("PAYEE_NM");
BUDGET_HEAD=rsMain.getString("BUDGET_HEAD")==null?"":rsMain.getString("BUDGET_HEAD");
PAYEE_NET_AMT=rsMain.getString("PAYEE_NET_AMT")==null?"":rsMain.getString("PAYEE_NET_AMT");
NET_PAY_MODE=rsMain.getString("NET_PAY_MODE")==null?"":rsMain.getString("NET_PAY_MODE");
TDS_ON_GST=rsMain.getString("TDS_ON_GST")==null?"":rsMain.getString("TDS_ON_GST");
SBI_TDS=rsMain.getString("SBI_TDS")==null?"":rsMain.getString("SBI_TDS");
GROSS_AMT=rsMain.getString("GROSS_AMT")==null?"":rsMain.getString("GROSS_AMT");
CHQ_PR_DT=rsMain.getString("CHQ_PR_DT")==null?"":rsMain.getString("CHQ_PR_DT");
CHQ_NO=rsMain.getString("CHQ_NO")==null?"":rsMain.getString("CHQ_NO");
CHQ_REMARKS=rsMain.getString("CHQ_REMARKS")==null?"":rsMain.getString("CHQ_REMARKS");
//ACT_YN=rsMain.getString("ACT_YN")==null?"":rsMain.getString("ACT_YN");

add_update="U";


}
rsMain.close();

}

%>



    <FORM method="post" name="form" id="form">
        <INPUT name="ins" id="ins" type="hidden">


        <div align="center">
            <table class="table table-striped table-bordered">

                <tr>
                    <td align="left"><strong>Cheque PRID: </strong></td>
                    <td colspan="3">
                        <p class="style2">
                            <strong><%=CHQ_PRID %></strong>
                            <INPUT name="ins" type="hidden" id="ins">
                            (Autogenerated)</p>                    </td>
                </tr>
                <tr>
                    <td><strong>Payment Type: * </strong></td>
                    <td colspan="3"><span class="style3">
                            <SELECT name="PAY_TYPE" id="paytype" onChange="change();" class="drpdwn" required>
                                <OPTION value="">Select</OPTION>
                                <OPTION value="PFMS" <% if (PAY_TYPE.equals("PFMS")){ out.print("selected");}%> data-sync="PFMS">PFMS</OPTION>
                                <OPTION value="IFMS" <% if (PAY_TYPE.equals("IFMS")){ out.print("selected");}%>>IFMS </OPTION>
                                <OPTION value="OTH" <% if (PAY_TYPE.equals("OTH")){ out.print("selected");}%>>OTHERS </OPTION>
                            </SELECT>
                        </span> </td>
                </tr>

                <tr>
                    <td><strong>PFMS No : * </strong></td>
                    <td><span class="style3">
                            <input name="PFMS_ADV_NO" type="text" id="PFMS_ADV_NO" placeholder="PFMS Number" value="<%=PFMS_ADV_NO%>" maxlength="20" required/>
                        </span></td>
                    <td> Date: * </td>
                    <td><span class="style3">
                            <input name="PAY_ORD_DT" type="text" id="PAY_ORD_DT" onClick="javascript:NewCssCal('PAY_ORD_DT','ddMMMyyyy')" placeholder="Pay Order Date" readonly="true" AUTOCOMPLETE="off" value="<%=PAY_ORD_DT%>" required />

                  </span></td>
                </tr>
                <tr>
                    <td><strong>Budget Head: * </strong></td>
                    <td colspan="3"><span class="style3">
                            <select name="BUDGET_HEAD" id="BUDGET_HEAD" class="drpdwn" required>
<option value="">Select</option>
<option value="VIGRANT" <% if (BUDGET_HEAD.equals("VIGRANT")){ out.print("selected");}%>>VI Grant</option>
<option value="KHGRANT" <% if (BUDGET_HEAD.equals("KHGRANT")){ out.print("selected");}%>>Khadi Grant </option>
<option value="PMEGP" <% if (BUDGET_HEAD.equals("PMEGP")){ out.print("selected");}%>>PMEGP</option>
<option value="ADB" <% if (BUDGET_HEAD.equals("ADB")){ out.print("selected");}%>>ADB</option>
<option value="SFURTI" <% if (BUDGET_HEAD.equals("SFURTI")){ out.print("selected");}%>>Sfurti</option>
<option value="OTH" <% if (BUDGET_HEAD.equals("OTH")){ out.print("selected");}%>>Others</option>
                            </select>
                        </span></td>
                </tr>
                <tr>
                    <td><strong>Payee Name: * </strong></td>
                    <td colspan="3"><span class="style3">
                            <input name="PAYEE_NM" type="text" id="PAYEE_NM" placeholder="Payee Name" value="<%=PAYEE_NM%>" maxlength="50" required />
                            
</span></td>
                </tr>
                <tr>
                    <td><strong>Gross Amount: * </strong></td>
                    <td colspan="3"><span class="style3">
                            <input name="GROSS_AMT" type="text" id="Num1" placeholder="Gross Amount" onKeyUp="calculateSum();" onKeyPress="return numbersonly(event);" value="<%=GROSS_AMT%>" maxlength="10" required/>
                        </span></td>
                </tr>
                <tr>
                    <td><strong>TDS on GST: </strong></td>
                    <td><span class="style3">
                            <input name="TDS_ON_GST" type="text" id="Num2" placeholder="TDS on GST" onKeyUp="calculateSum();" onKeyPress="return numbersonly(event);" value="<%=TDS_ON_GST%>" maxlength="10" required/>
                        </span>
                    <td>SBI TDS Amount:
                    <td><span class="style3">
                            <input name="SBI_TDS" type="text" id="Num3" placeholder="SBI TDS Amount" onKeyUp="calculateSum();" onKeyPress="return numbersonly(event);" value="<%=SBI_TDS%>" maxlength="10" required />
                        </span>
                <tr>
                    <td><strong>Payee Net Amount: </strong></td>
                    <td><span class="style3">
                            <input name="PAYEE_NET_AMT" type="text" id="Sum" placeholder="Net Amount" readOnly="true" value="<%=PAYEE_NET_AMT%>" />
                        </span></td>
                    <td>Net Payment Mode: </td>
                    <td><span class="style3">
                            <select name="NET_PAY_MODE" id="paymode" class="drpdwn">
                                <option value="">Select</option>
                                <option value="PFMS" <% if (NET_PAY_MODE.equals("PFMS")){ out.print("selected");}%>>PFMS</option>
                                <option value="DD" <% if (NET_PAY_MODE.equals("DD")){ out.print("selected");}%>>DD</option>
                                <option value="RTGS" <% if (NET_PAY_MODE.equals("RTGS")){ out.print("selected");}%>>RTGS</option>
                                <option value="CHQ" <% if (NET_PAY_MODE.equals("CHQ")){ out.print("selected");}%>>Cheque</option>
                            </select>
                        </span></td>

                    <input name="CHQ_PR_DT" type="hidden" id="CHQ_PR_DT" onClick="javascript:NewCssCal('CHQ_PR_DT','ddMMMyyyy')" readonly="true" AUTOCOMPLETE="off" value="<%=CHQ_PR_DT%>" />
              
                <tr>
                    <td><strong>Cheque Remarks: </strong></td>
                    <td colspan="3"><span class="style3">
                            <input name="CHQ_REMARKS" type="text" id="CHQ_REMARKS" placeholder="Remarks" value="<%=CHQ_REMARKS%>" maxlength="100" />
							<INPUT name="ACT_YN" type="hidden" id="ACT_YN" value="Y">
                        </span></td>
                </tr>
            </table>
        </div>

        <DIV align="center"><INPUT type="button" name="Submit" class="buttonBlue" onClick="submitform();" value="SAVE">
        </DIV>

    </FORM>
    <%

if ((String)request.getParameter("ins")!=null){
//CHQ_PRID=(String) request.getParameter("CHQ_PRID")==null?"":(String) request.getParameter("CHQ_PRID").trim(); 
PAY_TYPE =(String) request.getParameter("PAY_TYPE")==null?"":(String) request.getParameter("PAY_TYPE").trim(); 
PFMS_ADV_NO =(String) request.getParameter("PFMS_ADV_NO")==null?"":(String) request.getParameter("PFMS_ADV_NO").trim(); 
PAY_ORD_DT=(String) request.getParameter("PAY_ORD_DT")==null?"":(String) request.getParameter("PAY_ORD_DT").trim();
BUDGET_HEAD=(String) request.getParameter("BUDGET_HEAD")==null?"":(String) request.getParameter("BUDGET_HEAD").trim();
PAYEE_NM=(String) request.getParameter("PAYEE_NM")==null?"":(String) request.getParameter("PAYEE_NM").trim();
GROSS_AMT=(String) request.getParameter("GROSS_AMT")==null?"":(String) request.getParameter("GROSS_AMT").trim();
TDS_ON_GST=(String) request.getParameter("TDS_ON_GST")==null?"":(String) request.getParameter("TDS_ON_GST").trim();
SBI_TDS=(String) request.getParameter("SBI_TDS")==null?"":(String) request.getParameter("SBI_TDS").trim();

PAYEE_NET_AMT=(String) request.getParameter("PAYEE_NET_AMT")==null?"":(String) request.getParameter("PAYEE_NET_AMT").trim();
NET_PAY_MODE=(String) request.getParameter("NET_PAY_MODE")==null?"":(String) request.getParameter("NET_PAY_MODE").trim();
CHQ_PR_DT=(String) request.getParameter("CHQ_PR_DT")==null?"":(String) request.getParameter("CHQ_PR_DT").trim();
CHQ_NO=(String) request.getParameter("CHQ_NO")==null?"":(String) request.getParameter("CHQ_NO").trim();
CHQ_REMARKS=(String) request.getParameter("CHQ_REMARKS")==null?"":(String) request.getParameter("CHQ_REMARKS").trim();
ACT_YN=(String) request.getParameter("ACT_YN")==null?"":(String) request.getParameter("ACT_YN").trim();


String a=PAY_ORD_DT;
StringBuffer qryUpdate = new StringBuffer();


if (add_update.equals("I")) {
		
ResultSet rsMax = db.execSQL("SELECT SEQCHQPRID.NEXTVAL as CHQ_PRID  FROM DUAL");
 while (rsMax.next()){
 CHQ_PRID=rsMax.getString("CHQ_PRID")==null?"":rsMax.getString("CHQ_PRID");
 }
 rsMax.close();


qryUpdate.append(" INSERT INTO ACC_CHQ_PRINT ");
qryUpdate.append("( PAY_TYPE ,");
qryUpdate.append("PFMS_ADV_NO ,");
qryUpdate.append("PAY_ORD_DT, ");
qryUpdate.append(" BUDGET_HEAD ,");
qryUpdate.append("PAYEE_NM , ");
qryUpdate.append("GROSS_AMT , ");
qryUpdate.append("TDS_ON_GST , ");
qryUpdate.append("SBI_TDS ,");
qryUpdate.append("PAYEE_NET_AMT ,");
qryUpdate.append("NET_PAY_MODE ,");
qryUpdate.append("CHQ_PR_DT, ");
qryUpdate.append("CHQ_NO ,");
qryUpdate.append("CHQ_REMARKS ,");
qryUpdate.append("ACT_YN ,");
qryUpdate.append("CHQ_PRID ");
qryUpdate.append( ") VALUES (?,?,?,?,?, ?,?,?,?,?, ?,?,?,?,?) ");

}

else {
try{

		
qryUpdate.append("	UPDATE ACC_CHQ_PRINT SET ");
qryUpdate.append("	PAY_TYPE  = ?, ");
qryUpdate.append("	PFMS_ADV_NO  = ?, ");
qryUpdate.append("	PAY_ORD_DT = ?, ");
qryUpdate.append("	BUDGET_HEAD= ?, ");
qryUpdate.append("	PAYEE_NM= ?, ");
qryUpdate.append("	GROSS_AMT = ?, ");
qryUpdate.append("	TDS_ON_GST = ?, ");
qryUpdate.append("	SBI_TDS= ?, ");
qryUpdate.append("	PAYEE_NET_AMT= ?, ");
qryUpdate.append("	NET_PAY_MODE= ?, ");
qryUpdate.append("	CHQ_PR_DT= ?,");
qryUpdate.append("	CHQ_NO= ?,");
qryUpdate.append("	CHQ_REMARKS= ? ,");
qryUpdate.append("  ACT_YN=? ");
qryUpdate.append(" WHERE CHQ_PRID = ?");


}

catch(Exception e){
out.print(e.toString());
}

}

values.add(PAY_TYPE); pstm.add ("L");
values.add(PFMS_ADV_NO); pstm.add ("L");
values.add(PAY_ORD_DT); pstm.add ("L");
values.add(BUDGET_HEAD); pstm.add ("L");
values.add(PAYEE_NM); pstm.add ("L");
values.add(GROSS_AMT); pstm.add ("L");
values.add(TDS_ON_GST); pstm.add ("L");
values.add(SBI_TDS); pstm.add ("L");
values.add(PAYEE_NET_AMT); pstm.add ("L");
values.add(NET_PAY_MODE); pstm.add ("L");
values.add(CHQ_PR_DT); pstm.add ("L");
values.add(CHQ_NO); pstm.add ("L");
values.add(CHQ_REMARKS); pstm.add ("L");
values.add(ACT_YN); pstm.add ("L");
values.add(CHQ_PRID); pstm.add ("L");

db.setSqlValue(qryUpdate.toString()); 
db.setValues(values,pstm); 
db.executeUpdate(); 
values.clear(); 
pstm.clear();
response.sendRedirect("savemsg.jsp");
}
db.close(); 


%>
    <script>
        function calculateSum() {
            var num1 = parseFloat(document.getElementById("Num1").value);
            var num2 = parseFloat(document.getElementById("Num2").value);
            var num3 = parseFloat(document.getElementById("Num3").value);
            var sum = parseFloat('0' + num1) - parseFloat('0' + num2) - parseFloat('0' + num3);
            document.getElementById("Sum").value = sum;


        }

       function change() {
         if (document.getElementById('paytype').value == 'PFMS')
                document.getElementById("paymode").value = 'PFMS';
      };


//function change(){
//   
//  if(document.getElementById("paytype").value=="PFMS"){
//      document.getElementById("paymode").value = 'PFMS';
//	  document.getElementById("paymode").disabled = true;
//  } else {
//    document.getElementById("paymode").disabled = false;
//  } 
//                  
//} 


    </script>

    </FORM>
</BODY>

</HTML>
